[package]
name = "gap-check"
version = "0.1.0"
edition = "2024"
default-run = "gap-check"

[dependencies]
arrayvec = "0.7.6"
chrono = "0.4"
chrono-tz = "0.10"
color-eyre = "0.6"
dotenvy = "0.15.7"
imessage-database = "3.3.2"
indicatif = "0.18"
ouroboros = "0.18"
regex = "1.12"
rusqlite = "0.38.0"
serde = "1"
serde_json = "1"
tabled = "0.20"

[[bin]]
name = "extract-fixtures"
path = "src/bin/extract_fixtures.rs"

[dev-dependencies]
hex = "0.4.3"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = true
