[package]
name = "me-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.8"
chrono = "0.4.44"
chrono-tz = "0.10.4"
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
dotenvy = "0.15.7"
imessage-database = "4.2.0"
indicatif = "0.18.6"
ouroboros = "0.18.5"
regex = "1.13.1"
rusqlite = "0.40.0"
serde = "1.0.229"
serde_json = "1.0.151"
tabled = "0.22.0"

[dev-dependencies]
hex = "0.4.3"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = true
